{{- $ctx := .Values }}
{{- range .Values.certificates }}
{{- if not (hasKey . "issuerRef") }}
{{- $certName := printf "%s-%s" .name $ctx.global.envSuffix | trimSuffix "-" }}
{{- $issuerName := printf "selfsigned-issuer-%s" $ctx.global.envSuffix | trimSuffix "-" }}
{{- $domainSelector := .domain }}
{{- $selectedDomain := index $ctx.global.domains $domainSelector }}
{{- $domainName := printf "%s.%s" $certName $selectedDomain }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $domainName }}
{{- if hasKey . "namespace" }}
  namespace: {{ .namespace }}
{{- else}}
  namespace: {{ $ctx.global.certNamespace }}
{{- end }}  
spec:
  secretName: {{ $domainName }}
  dnsNames:
  - "{{ $domainName }}"
  issuerRef:
    name: {{ $issuerName }}
{{- end }}
{{- end }}
