{{- $ctx := .Values }}
{{- range .Values.issuers }}
  {{- range $name, $maps := .secrets }}
---
kind: Secret
apiVersion: v1
metadata:
  name: {{ $name }}
  namespace: {{ $ctx.global.issuerNamespace }}
type: Opaque
data:
    {{- range $key, $value := $maps }}
  {{ $key }}: {{ $value }}
    {{- end }}
  {{- end }}
{{- end }}