global:
  domains:
    tdg: onprem-rke-demo.tdg-int.net
    its: onprem-rke-demo.its-software-services.com
  certNamespace: istio-system
  issuerNamespace: cert-manager
  #envSuffix: ''
  letsEncryptEnv: test #prod
  solvers:
    - dns01:
        route53:
          region: eu-central-1
          accessKeyID: AKIAIOSFODNN7EXAMPLE
          secretAccessKeySecretRef:
            name: aws-route53-credentials
            key: secret-access-key
          # you can also assume a role with these credentials
          role: arn:aws:iam::YYYYYYYYYYYY:role/dns-manager
      selector:
        dnsZones:
          - "tdg-int.net"
    - dns01:
        cloudDNS:
          project: its-artifact-commons
          serviceAccountSecretRef:
            name: gcp-cloud-dns-account-key
            key: service-account.json
issuers:
  - name: lets-encrypt-issuer
    email: seubpong.mon@truedigital.com
    secrets:
      aws-route53-credentials:
        secret-access-key: secretValue

certificates:
  - name: dex-idp
    domain: its
    issuerRef: lets-encrypt-issuer

  - name: k8s-auditlog
    issuerRef: lets-encrypt-issuer
    isWildcard: true
    secretName: override-secret-cert
    domain: tdg
